services:
  # OpenWebUI for chat interface
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: simplemcpo-openwebui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://agentic-api:8000
      - OPENAI_API_KEY=dummy-key # Required but can be dummy for local APIs
      - WEBUI_AUTH=False # Disable authentication for development
      - WEBUI_NAME=Agentic Template Chat
      - WEBUI_URL=http://localhost:3000
    volumes:
      - openwebui-data:/app/backend/data
    restart: unless-stopped
    networks:
      - agentic-network

networks:
  agentic-network:
    driver: bridge

volumes:
  openwebui-data:
